import { useState } from 'react';
import TopBar from '../components/TopBar';
import Tabs from '../components/Tabs';
import ScoringConfigForm from '../components/ScoringConfigForm';
import UsersTable from '../components/UsersTable';
import AuditTable from '../components/AuditTable';
import styles from './Admin.module.css';

const TABS = [
  {
    id: 'config',
    label: 'Scoring configuration',
  },
  {
    id: 'users',
    label: 'Users',
  },
  {
    id: 'audit',
    label: 'Audit trail',
  },
];

const INTROS = {
  config:
    'These weights drive every new score, the band a transaction lands in, and the risk-assessment table printed on each STR.',

  users:
    'Everyone with access to the console and the role they sign in with.',

  audit:
    'Every sign-in, ingestion, score, analyst action, export and STR generated by the engine.',
};

function SettingsIcon() {
  return (
    <svg
      viewBox="0 0 24 24"
      aria-hidden="true"
    >
      <circle cx="12" cy="12" r="3" />
      <path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-1.8 1.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-2.5V20a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1-1.8-1.8.1-.1a1.7 1.7 0 0 0 .3-1.9 1.7 1.7 0 0 0-1.6-1H6v-2.5h.2a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9l-.1-.1 1.8-1.8.1.1a1.7 1.7 0 0 0 1.9.3 1.7 1.7 0 0 0 1-1.6V5h2.5v.2a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1 1.8 1.8-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v2.5h-.2a1.7 1.7 0 0 0-1.6 1Z" />
    </svg>
  );
}

function UsersIcon() {
  return (
    <svg
      viewBox="0 0 24 24"
      aria-hidden="true"
    >
      <circle cx="9" cy="8" r="3" />
      <path d="M3.5 19c.5-3.2 2.3-5 5.5-5s5 1.8 5.5 5" />
      <path d="M15 6.5a3 3 0 0 1 0 5.8M17 14c2.1.5 3.4 2.1 3.8 4.5" />
    </svg>
  );
}

function AuditIcon() {
  return (
    <svg
      viewBox="0 0 24 24"
      aria-hidden="true"
    >
      <path d="M6 3h9l4 4v14H6V3Z" />
      <path d="M15 3v5h4M9 12h6M9 16h6" />
    </svg>
  );
}

export default function Admin() {
  const [tab, setTab] = useState('config');

  const tabIcon =
    tab === 'config' ? (
      <SettingsIcon />
    ) : tab === 'users' ? (
      <UsersIcon />
    ) : (
      <AuditIcon />
    );

  return (
    <>
      <TopBar active="admin" />

      <main className={styles.page}>
        <header className={styles.head}>
          <div>
            <h1 className={styles.title}>
              Administration
            </h1>

            <p className={styles.subtitle}>
              {INTROS[tab]}
            </p>
          </div>

          <div className={styles.motto}>
            <strong>
              Detect&nbsp; • &nbsp;Analyse&nbsp; • &nbsp;Prevent
            </strong>

            <span>
              Safer Transactions. Stronger Trust.
            </span>
          </div>
        </header>

        <section className={styles.panel}>
          <div className={styles.tabHeader}>
            <Tabs
              tabs={TABS}
              active={tab}
              onChange={setTab}
            />
          </div>

          <div className={styles.tabContent}>
            <div className={styles.activeSection}>
              <span className={styles.activeIcon}>
                {tabIcon}
              </span>

              <div className={styles.activeText}>
                <span className={styles.activeTitle}>
                  {TABS.find(
                    (item) => item.id === tab
                  )?.label}
                </span>

                <span className={styles.activeDescription}>
                  {tab === 'config'
                    ? 'Configure how the fraud engine evaluates transactions.'
                    : tab === 'users'
                    ? 'Manage console users and their assigned roles.'
                    : 'Review activity and actions performed in the engine.'}
                </span>
              </div>
            </div>

            {tab === 'config' && (
              <ScoringConfigForm />
            )}

            {tab === 'users' && (
              <UsersTable />
            )}

            {tab === 'audit' && (
              <AuditTable />
            )}
          </div>
        </section>

        <footer className={styles.footer}>
          <span>
            Signed in to the UFDE administration console.
          </span>

          <span>
            © 2026 UFDE. All rights reserved.
          </span>
        </footer>
      </main>
    </>
  );
}